spring.application.name=bibliotecavirtual
spring.config.import=file:.env[.properties]

# PostgreSQL Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://db.prisma.io:5432/postgres?sslmode=require}
spring.datasource.username=${DB_USERNAME:765a9ed4df9a1f5da461a6ae150bf2185180d071854018612277cf9c840f7ffe}
spring.datasource.password=${DB_PASSWORD:sk_uzBD_QrjgW7WTOrKzica4}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true